### ISSUE TITLE
動画タイトルについて

### ISSUE THREAD

**Issue by omote007** [omote009/mfc#1]
植田真梨恵、「わかんないのはいやだ」 MVを公開【音楽ニュース】

ドローンで野鳥撮影　ＦＰＶ画像付　シギかチドリの集団飛翔

**Comment by omote009** [comment]
了解。とりあえず「音楽ニュース」「ＦＰＶ」を省くようにメンテしてみる。

**Comment by omote007** [comment]
“酸欠少女”さユり、YKBKによる「ミカヅキ」の2.5次元パラレルなMVが解禁

↑【音楽ニュース】で出てきたものと同じような動画が流れる。何か削除する共通点はないか

**Comment by omote007** [comment]
動画タイトルからアーティスト名だけでなくタイトル文まで消えてしまう。おそらくアーティスト名に含まれる文字が消えている

Music Videoのスペースありでも検索引っかかるように

**Comment by omote007** [comment]
アンダーグラフ/、こころに響くと話題の新曲「こころ」MV公開(Auto)
https://www.youtube.com/watch?v=txa3MYB-1xc

Alexandrosアレキサンドロス「Girl A」川上洋平おまけ映像の新曲MV公開！おまけ映像は川上洋平&松坂桃李・主演ドラマのオープニング曲！２０１５年１２月２日発売
https://www.youtube.com/watch?v=qTbPaUO0ylA

片平里菜の新MV「誰にだってシンデレラストーリー」はドラマ仕立て、五島夕夏＆成田凌が出演
https://www.youtube.com/watch?v=OY3wmhXCLt8

【Rの法則】KANA-BOON　なんでもねだりMVの秘密　20150513【2】
https://www.youtube.com/watch?v=5oLWe-QKwEs

「talking」KANA-BOON　フル　pv
https://www.youtube.com/watch?v=cmJyFKjELak

SEKAI NO OWARI シングル『ANTI-HERO』MV作成の詳細コメント！
https://www.youtube.com/watch?v=uxaKPzMCUjs

ZIP ANTI-HERO MV密着取材 SEKAI NO OWARI セカオワ 2015年 7月24日
https://www.youtube.com/watch?v=Xcb7_u2pfYg

chay 「あなたに恋をしてみました」PV 「デート～恋とはどんなものかしら～」の主題歌
http://localhost:8080/mfc/moviePlay/?key=em8y429mBVQ&sel=eXxDU86GGN#here

西野カナ in〜《♪君は天然色 -めちゃ可愛い！》Special MV【HD】
https://www.youtube.com/watch?v=E8UBWAhy-PY

君って 西野カナ【カラオケ/歌詞付き/フル】ドラマ主題歌やpvのfullなどliveでも鉄板曲 ゴスペラーズのカバーやピアノや合唱などでも人気歌ってみたで人気 西野かなの新曲は歌ってみたや吹奏楽もいい
https://www.youtube.com/watch?time_continue=34&v=mWmtpktM1Vs

恋する気持ち 西野カナ【カラオケ/歌詞付き/フル】歌ってみたやpvのfullなどliveでも人気 ピアノや合唱や吹奏楽のほかカバーでも人気 西野かなのliveは常に新曲気分でいい
https://www.youtube.com/watch?v=1XlewvfY3Ec

**Comment by omote009** [comment]
ここまでの指摘点にはみんな対応した。
単体テストまではOK。マージして確認よろしく。

**Comment by omote007** [comment]
●(阿部真央)
手書きPV/じゃあ、何故/阿部真央/ver.アラビヨ
https://www.youtube.com/watch?v=W9Lp2Kmxch0

●(UPLIFT SPICE)
1080pHD UPLIFT SPICE オメガリズム
https://www.youtube.com/watch?v=wxE0cyBfN04

[AMV] UPLIFT SPICE Omega Rythm
https://www.youtube.com/watch?v=mLmrU3yLcmY

●( Le Lien)
SuddenAttack SACW Rualice. vs LE-LIEN PV 青　Cラッシュ止め 1/2
https://www.youtube.com/watch?v=JTQ3Jk3G4oA

9月28日Le lien PV
https://www.youtube.com/watch?v=9iI6HtnMLoM

●(チャットモンチー)
東京倉庫物語【第61話】東京倉庫がチャットモンチーのMVを作った理由
https://www.youtube.com/watch?time_continue=8&v=ucYIaVqQozA

●(黒木渚)
黒木渚「革命」MV MAKING
https://www.youtube.com/watch?v=Ee2BP8w3AVA

**Comment by omote007** [comment]
●(私立恵比寿中学)
「OPV」私立恵比寿中学『PLAYBACK』

**Comment by omote009** [comment]
「OPV」私立恵比寿中学『PLAYBACK』まで対応した。単体テストまではOK。
一旦、長くなってきたので、一回目はクローズしておく。以後、2回めのIssueに書いて。
