### ISSUE TITLE
動画タイトルフィルター対応（11月16日以降発見分）

### ISSUE THREAD

**Issue by omote009** [omote009/mfc#2]
整理のために、ISSUEをわけた。以降はこっちにコメントして。

**Comment by omote009** [comment]
踊ってみた　とか、DVD予告とかのありえそうなパターンを先回りしてつぶす対応をした。
最新バージョンでマージして試して。

**Comment by omote007** [comment]
了解

**Comment by omote007** [comment]
どのファイルをマージすればいい？

**Comment by omote009** [comment]
ArtistVideoLinkService.java だけ。

変更箇所とファイルの確認はGitHubでできるよ。
やり方を添付しとく。

2015-11-17 15:23 GMT+09:00 naoki omote notifications@github.com:

**Comment by omote007** [comment]
添付がどこにあるのかわからない
→　GMailのほうを見て。そこにある。

**Comment by omote007** [comment]
●「Mayu」の検索で別の「MAYU」が引っかかった。

●オズ
【Rejet】オズと秘密の愛 PV
https://www.youtube.com/watch?v=XcM614l_FYo

**Comment by omote007** [comment]
●藤原さくら
藤原さくら「Walking on the clouds」MV！『a la carte』の中の名曲。
https://www.youtube.com/watch?time_continue=67&v=tXnR2is6V_w

●BRADIO
BRADIO「HOTELエイリアン」MVでキャプテンアフロがメンバー救出
https://www.youtube.com/watch?v=0wq8uBrISfg

**Comment by omote009** [comment]
GMailの方で見て。

2015-11-17 21:45 GMT+09:00 naoki omote <notifications@github.com>:

**Comment by omote009** [comment]
PVを選択肢からはずした版コミットした。
藤原さくらとBRADIOの件対応済。
ArtistVideoLinkService.java　のみマージして。

**Comment by omote007** [comment]
●shepherd
Avenged Sevenfold - Shepherd Of Fire [Official Music Video]

●PAN
I Believe (Pan Music Video) Christina Perri

●荒川ケンタウロス
荒川ケンタウロス、新曲ミュージックビデオは漫画家・長尾謙一郎とコラボレーション

●トレモノ
土ミツ　トレモノ　未完成.wmv

●CREAM
Red Velvet 레드벨벳_Ice Cream Cake_Music Video

Manila Luzon - "Ice Cream" ft Andre Xcellence [official music video]

Tujamo & Danny Avila - Cream (Official Music Video)

●テツコ
【MV】さよならテツコちゃん SHAKABOOZ & 大阪ミュウミュウ

●Against All Enemies
Against All Enemies.wmv

**Comment by omote007** [comment]
●藍井エイル
「IGNITE」AMV 藍井 エイル Cover と歌詞

**Comment by omote009** [comment]
対応した。いったん、第二弾もここでクローズする。
