### ISSUE TITLE
攻撃されてる？？

### ISSUE THREAD

**Issue by omote007** [omote009/mfc#3]
さっきアナリティクスで訪問ユーザー数確認したら48人になってた。
ただ、その内の44人は海外からのアクセスで訪問時刻も固まってて滞在時間も短すぎる。
ちなみに前日の訪問は２人。

普通のユーザーとは考えにくい。なんかの攻撃かなあ？

**Comment by omote009** [comment]
たぶんね。

2015年11月17日 15:05 naoki omote notifications@github.com:

**Comment by omote009** [comment]
スクライピングかもしれないね。
とりあえず、アクセスカウンタ以外の実害はなさそうなので、クローズしとく。
