### ISSUE TITLE
タイトルフィルター対応第三段階

### ISSUE THREAD

**Issue by omote009** [omote009/mfc#4]
アーティスト名先頭ルール適用したのをうけて、一旦第二弾をクローズした。
整理のため、こっから見つけたのは、こっちに対応して。

**Comment by omote009** [comment]
[XXX]　が正式名称のアーティストの場合、XXXの部分が正規表現で解釈されてしまい、タイトルから消える問題が発生（・[Alexandros]）

**Comment by omote009** [comment]
[Alexandros]でも、正規表現として処理されないように対応した。

**Comment by omote007** [comment]
マージ完了

**Comment by omote007** [comment]
●Stereo Osaka
Stereo Osaka 2015.08.08 HMV三宮VIVRE 2部 Edge Dub Monkeyz
Stereo Osaka(ステレオ大阪)HMV三宮店　「Endelss Dokidoki Mode」
Stereo Osaka in HMV Sannomiya
Stereo Osaka(ステレオ大阪)HMV三宮店　「Osaka GEISHA Dancing」
Stereo Osaka インストアライブ HMV三宮(一部) 2015.08.08
Stereo Osaka(ステレオ大阪)HMV三宮店　「Electron」

**Comment by omote009** [comment]
HMVははじくように対応。AMVは単純にやると、曲名でひっかかるので、今回はパス。

**Comment by omote007** [comment]
マージ完了

**Comment by omote007** [comment]
●SpecialThanks
【SpecialThanks】"I MY ME MINE"ミュージックビデオ撮影 - 2012.11月吉日

**Comment by omote007** [comment]
●井手綾香
井手綾香 - 「235」「消えてなくなれ、夕暮れ」Music Videoスペシャル先行映像

**Comment by omote009** [comment]
先行のキーワードがつく複数のケースに対応した。

**Comment by omote009** [comment]
フィルター条件を改善したので、PVも対象に復活させようと思う。
一応、今まででてきたイレギュラー（クラブのPV含む）は問題なくはじかれるのを確認した。
どう思う？

**Comment by omote007** [comment]
復活させたい。植田真梨恵がすべてＰＶやったし

**Comment by omote009** [comment]
復活させた。テストしてみたら、植田真梨恵のPVきっちりとれた。PV復活版をマージして。

**Comment by omote007** [comment]
●Яeal
♥ яeal нorses #2 | ♫ music video ♫

**Comment by omote007** [comment]
マージ完了！

**Comment by omote007** [comment]
●I-RabBits
[I-Rabbits MMV concert] Part

**Comment by omote007** [comment]
●lalala
LALALA - THAITANIUM (Official Music video)
https://www.youtube.com/watch?v=3dRgEgyozHo

●GIRLFRIEND
SOLIDEMO / 「Girlfriend」MUSIC VIDEO（Short ver.）

**Comment by omote009** [comment]
12月2日連絡分対応。だんだん、レアなものが増えてくるなあ。

**Comment by omote007** [comment]
マージ完了！

**Comment by omote007** [comment]
●LiSA
LiSA Empty MERMAID MV 特殊メイク 黒い人魚

●Little Glee Monster
Little Glee Monster 『好きだ。』MV SELF REVIEW

**Comment by omote009** [comment]
対応した。あわせて、CheckStyleかけて、JAVAの文法上の指摘点をいくつか直した。
なので、今回は、マージする変更ファイルが多くなってる。

**Comment by omote007** [comment]
●蜜
【MV】蜜恋(ハニー)ライアー！？　[しゅみしゅみ/仲谷明香]

**Comment by omote009** [comment]
とりあえず、長くなってきたので、クローズする。
連絡貰った分の対応は終わった。
