### ISSUE TITLE
タイトルフィルター対応第四段階

### ISSUE THREAD

**Issue by omote009** [omote009/mfc#5]
今後、こっちに書いて。

**Comment by omote007** [comment]
●LiSA
LiSA Empty MERMAID MV 特殊メイク 黒い人魚

●Emerald
Emerald Aisles (PV) / Emerald Aisles
【MV】EMERALD／ICE ELEMENT

**Comment by omote007** [comment]
●Яeal
♥ яeal нorses #2 | ♫ music video ♫
Яeal†waR　PV

**Comment by omote007** [comment]
● wacci
wacci「大丈夫」mv

●モハメド
モハメド・アヴドゥル ＆ マジシャンズレッド PV

**Comment by omote009** [comment]
モハメドは対応した。でも、wacciのこれは無理。

**Comment by omote007** [comment]
了解

**Comment by omote007** [comment]
●SEKIRARA
Sekirara Candy Anime PV
●Mayu
【MAYU】Love Logic【オリジナル・MMD-PV】
Mayu Wakisaka "24 Hours" (Official Music Video)
Mayu Wakisaka "Once" (Official Music Video)

**Comment by omote009** [comment]
Sekirara Candy Anime PV  と　【MAYU】Love Logic【オリジナル・MMD-PV】　は対応した。
Mayu Wakisaka　のは無理。このパターン、Mayu Wakisakaさんだと考えれば、とても真っ当なので。

**Comment by omote007** [comment]
●天才バンド
天才バンド、ニューアルバムよりリードトラック「ロックジェネレーション」MVを公開

●TAMTAM
We've Got Wings // TAMTAM // Official Music Video directed by Roxana Vilk
tamtam // Gender Game // Official Music Video

●ecosystem
AMV Gintama | Renho Arc. | Dilemma by Ecosystem
secret/ecosystem 自作MV

●NANOSCALE
【NANOSCALE TV vol.4】～PV撮影編～

●Azumi
「AZUMI幕末編」イメージPV1
「AZUMI幕末編」イメージPV2
AZUMI-あずみ-の小山ゆう最新作『雄飛 ゆうひ』PV

**Comment by omote007** [comment]
●LAMP IN TERREN
LAMP IN TERREN - 緑閃光 |MV Reaction|
LAMP IN TERREN - ボイド |MV Reaction|
LAMP IN TERREN - Mei |MV Reaction|

**Comment by omote007** [comment]
●The BEG
The BEG - PV撮影オフショット集 -

**Comment by omote007** [comment]
●Emerald
Emerald Aisles (PV) / Emerald Aisles

**Comment by omote009** [comment]
1月9日から20日分対応した。
ただ、Emerald Aisles (PV) / Emerald Aisles　は無理。 Emerald Aislesってアーティストいるし。
We've Got Wings // TAMTAM // Official Music Video　も同様。
最近、類似アーティスト抽出の開発を再開したので、ソースの変更がいっぱいあるけど、このフィルター対応で変更したのは、ArtistVideoLinkService.java　だけだから注意して。

**Comment by omote007** [comment]
●HEADLAMP
HEADLAMP 『ウチュウイチ』 (OFFICIAL VIDEO) 
●SHE'S
SHE'S/ Leave Me (MV)

でも動画追加されるようにしたい

**Comment by omote007** [comment]
あと、またマージがうまくいかないから次の土曜日にでも教えてほしい。

**Comment by omote009** [comment]
了解

**Comment by omote009** [comment]
OFFICIAL VIDEO　も対象に加えた版アップした。

**Comment by omote007** [comment]
ありがとう

2016-02-09 21:30 GMT+09:00 tadashi.omote notifications@github.com:

**Comment by omote009** [comment]
類似アーティスト取得機能アップしたから、一旦コメントを切るね。
